sudo: required
language: node_js
node_js:
- '8'
install:
  - npm install --build-from-source
cache:
  directories:
    - "node_modules"
services:
- docker
env:
  global:
  - REGISTRY_USER=wericko123
  - secret: mcUCykGm4bUZlsaW6AxrIMFzuAYjA98VIz6YmYTmM0/8sp/B/54JtQS/j0ehCD6B5BwyW6diVcaQA2c7bovI23GyeTT+TgfkuKRkzDcoY51ZsMDdsflJ94zV7TEIS31eCeq42IBYdHZeVZp/L7EXOzFjVmvYhboJiwnsPybpCfpIH369fjYKuVmutccD890nP8Bzg8iegssVldgsqDagkuLy0wObAVH0FKnqiIPtFoMf3mDeVmK2AkF1Xri1edsPl4wDIu1Ko3RCRgfr6NxzuNSh6f4Z6zmJLB4ONkpb3fAa9Lt+VjJjdSjCBT1OGhJdP7NlO5vSnS5TCYvgFqNSXqqJx9BNzZ9/esszP7DJBe1yq1aNwAvJ7DlSzh5rvLyXR4VWHXRIR3hOWDTRwCsJQJctCLpbDAFJupuZDcvqvPNj8dY5MSCu6NroXMMFmxJHIt3Hdzr+hV9RNJkQRR4K5bR+ewbJ/6h9rjX6Ot6kIsjJkmEwx1jllxi4+gSRtNQ/O4NCi3fvHmpG2pCr7Jz0+eNL2d9wm4ZxX1s18ZSAZ5XcVJdx8zL4vjSnwAQoFXzmx0LcpK6knEgw/hsTFovSpe5p3oLcERfSd7GmPm84Qr8U4YFKXpeQlb9k5BK9MaQVqI4LyaM2h4Xx+wc0QlEQlUOfwD4B2XrAYXFIq1PAEic=
  - secure: GGAN1nGpFYJsrnuvwoFfWjHdFhSytfNnJddkplYHkSc2da1Qj8QRhUZtQTkIzpWGkuZh7a1YGIhNsVak2j3I8yT2zzJZQz6LWMtyaJy5ttt0Fo7IT1jSSOrtqmZamONhiTG6HZwxEf9FNaUUNcvivrAXFpALFeO42AIzidkpwYilISvp/F3JWB3Sbe9RYu5vqBqOt7Uly3uCse7jheJKJe6PAE6f2nLC8Wh13wOXOjwSyHeo+XGVoD8wk/PVwEv1awIawaqLccUnYtReLBSJTBDoaFls75HVZR/dGMNzzBhYhfTZUZPQgeOFwiCsnjtzb6rIQz2RVxWaL6yvoRRc+KMhZ+DXLwwnWwmx07NNKoA7dgB9xhoEIVcNmFqvS6S3htBevP5IjiQH9BqTZOwikmiBgsO31gla0JkSoY2eCK9t8oXc4S9bGuxW2W6zFZouFGYTMwQwwnt/FrUBcmnG0aXX+z/+YKbSQJfsxv/ZuKOnGzxw3B2IDTgCDUXNA9ePo7f0cae5kw6HLalRYaDWiY1JbMU9QbER7jNK6CIjf3J3JobM/isOamMxN2Xe4cN5tMH7avRZEOSNuj/aTKg+/hrEWh4mRf4KKput++FZfBQE90f119XTE+bJnbCkrygqcCneVjmL5uqerhiV5SRDXQ892YIpR6aRihIvjKirHwM=
  matrix:
  - USE_NETWORK=true
  - USE_NETWORK=false
before_script:
- docker pull erickorg/myrepo || true
script:
- docker build --pull --cache-from erickorg/myrepo --tag erickorg/myrepo .
- docker run erickorg/myrepo
after_script:
- docker images
before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push erickorg/myrepo
  on:
    branch: master