sudo: required

language: node_js

node_js:
- "8"

cache:
  directories:
    - "node_modules"

services:
  - docker

script:
  - docker build --tag ezpdf .
  - docker run ezpdf

after_script:
  - docker images
  